version: '3.7'

services:

   newman-extra:
      build: ./postman-newman-alpine
      container_name: newman-extra
      command:
         run Test-Lab-Reqres.in.postman_collection.json
         -e environments/Test-Lab-Environment.postman_environment.json
         -r htmlextra 
         --reporter-htmlextra-export ./reports/result-extra.html
      volumes:
         - ../../postman/collections/reqres:/etc/newman
